export type ChangelogType = "release" | "improvement" | "fix";

export type ChangelogItem = {
  version: string;
  date: string;
  title: string;
  description: string;
  type: ChangelogType;
  changes: string[];
  githubUrl?: string;
};

export const githubRepositoryUrl = "https://github.com/netalone10/BudgetIn";

export const changelogItems: ChangelogItem[] = [
  {
    version: "v1.9.2",
    date: "2026-05-09",
    title: "React Doctor fixes dan hardening input transaksi",
    description: "Rilis patch untuk membersihkan issue React/Next.js lint-doctor, memperkuat parsing transaksi, dan memastikan setting tipe budget kategori terbaca konsisten.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/commit/e5ffd4c`,
    changes: [
      "Memperbaiki temuan React Doctor di halaman dashboard, admin, auth, akun, budget, tagihan, kalender, cashflow, changelog, dan komponen UI terkait.",
      "Memperkuat parsing nominal transaksi agar input natural seperti ribuan/jutaan lebih aman dan konsisten.",
      "Membersihkan note transaksi dari hasil parsing agar catatan yang tersimpan lebih rapi.",
      "Memastikan pilihan kategori Fixed/Variable yang sudah tersimpan di database ikut terbaca pada data budget dan dashboard.",
    ],
  },
  {
    version: "v1.9.1",
    date: "2026-05-09",
    title: "Compatibility kategori budget type",
    description: "Rilis patch untuk menjaga kompatibilitas produksi saat kolom budget type belum tersedia di sebagian environment database.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/commit/fd4411f`,
    changes: [
      "Menambahkan fallback pada API kategori ketika kolom budget_type belum tersedia di database production.",
      "Menjaga alur tagihan, transaksi manual, cron bills, dan backup tetap berjalan tanpa bergantung langsung pada field budget type.",
      "Memastikan kategori lama tetap mendapatkan tipe Fixed/Variable melalui fallback dari nama kategori.",
    ],
  },
  {
    version: "v1.9.0",
    date: "2026-05-08",
    title: "Akun Demo, Audit Keamanan, dan Perbaikan Data Integrity",
    description: "Rilis mayor yang mengamankan akun demo dengan pembacaan-only, menjalankan audit lengkap terhadap seluruh codebase, dan memperbaiki beberapa issue kritis terkait presisi data dan race condition.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.9.0`,
    changes: [
      "Membatasi akun demo ke mode pembacaan-only — semua tombol aksi (tambah, edit, hapus, reset) tersembunyi, semua write API routes dikembalikan 403 Forbidden.",
      "Menambahkan banner Demo Mode dan countdown timer 15 menit yang otomatis logout jika tidak ada aktivitas.",
      "Memblokir password panjang (>128 karakter) untuk mencegah bcrypt DoS.",
      "Memperbaiki urutan validasi password — cek sama dengan password lama sebelum menjalankan bcrypt.compare yang mahal.",
      "Menambahkan pengecekan null CRON_SECRET agar endpoint cron tidak bisa di-bypass dengan string 'Bearer undefined'.",
      "Mengonversi Budget.amount dan SavingsGoal.targetAmount dari Float ke Decimal(19,4) untuk presisi data keuangan.",
      "Memperbaiki race condition di cron auto-record — transaction.create sekarang berada di dalam blok prisma.$transaction sehingga semua operasi bersifat atomic.",
      "Menambahkan foreign key constraint pada SavingsContribution.transactionId dengan onDelete: Cascade, mencegah data orphan saat transaksi dihapus.",
      "Mengoptimasi query transaksi akun — Prisma sekarang menggunakan take:limit dan database-level aggregation daripada memuat semua baris ke memori.",
    ],
  },
  {
    version: "v1.8.1",
    date: "2026-05-08",
    title: "Kontrol tipe budget kategori",
    description: "Rilis patch untuk menambahkan kontrol Fixed/Variable pada kategori budget dan memakai setting tersebut di semua tampilan budget.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.8.1`,
    changes: [
      "Menambahkan field budget type per kategori agar Fixed atau Variable bisa diatur dari Tools Kelola Kategori.",
      "Mengganti penentuan Fixed/Variable dari keyword hardcoded menjadi setting kategori yang tersimpan di database, dengan fallback untuk data lama.",
      "Memakai tipe budget kategori pada halaman Budget, dashboard Vs Budget, dan Status Budget untuk kalkulasi prorata dan progress bar.",
      "Menyertakan tipe budget kategori dalam API, data dashboard, backup/restore, dan sinkronisasi schema Prisma.",
    ],
  },
  {
    version: "v1.8.0",
    date: "2026-05-08",
    title: "Pembaruan visual dashboard dan progress budget",
    description: "Rilis minor untuk memperbarui tema visual dashboard, merapikan komponen UI utama, dan memperjelas progress budget terhadap total serta prorata.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.8.0`,
    changes: [
      "Mengubah dark theme ke gaya command center dengan surface gelap berlapis dan aksen Neon Lime yang lebih fokus.",
      "Merapikan sidebar, dashboard, form transaksi, kartu ringkasan, tab analytics, dan komponen UI agar lebih konsisten dengan token desain baru.",
      "Menambahkan progress bar budget berbasis total budget dengan marker prorata untuk kategori variable di halaman Budget, dashboard Vs Budget, dan Status Budget.",
      "Menambahkan dokumentasi produk, roadmap, dan TDD sebagai referensi pengembangan lanjutan.",
    ],
  },
  {
    version: "v1.7.3",
    date: "2026-05-08",
    title: "Perbaikan error server dan layout mobile",
    description: "Rilis patch untuk mencegah crash server component akibat timeout query Google Setup dan memperbaiki konten terpotong di mobile.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.3`,
    changes: [
      "Mencegah crash server component di halaman dashboard saat query Prisma ke Google Setup state timeout atau gagal.",
      "Error Google Setup sekarang di-graceful fallback ke state normal alih-alih menampilkan error boundary.",
      "Memperbaiki konten dashboard terpotong di mobile dengan mengganti overflow-x-hidden menjadi overflow-x-clip.",
      "Menambahkan min-w-0 di flex child layout dashboard agar konten tidak melebihi lebar parent.",
    ],
  },
  {
    version: "v1.7.2",
    date: "2026-05-07",
    title: "Perbaikan prompt real-time dan audit mobile",
    description: "Rilis patch untuk memastikan prompt tanpa jam eksplisit memakai waktu submit real-time dan memperkuat layout mobile di halaman utama dashboard.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.2`,
    changes: [
      "Mengabaikan waktu hasil AI seperti 08:00 atau 00:00 jika user tidak menyebut jam eksplisit di prompt transaksi.",
      "Memastikan prompt seperti beli ketoprak 20rb cash dicatat dengan waktu submit real-time Asia/Jakarta.",
      "Memperketat instruksi AI agar tidak membuat preset jam untuk pagi, siang, sore, malam, atau tadi tanpa angka jam eksplisit.",
      "Menambahkan test regresi untuk menjaga fallback waktu prompt tetap real-time.",
      "Menghapus blok Input, Output, dan Rhythm dari hero dashboard agar user langsung masuk ke fitur utama.",
      "Merapikan mobile view dashboard, detail akun, budget, calendar, cashflow, tipe akun, tabungan, dan tagihan rutin agar nominal penting tidak tersembunyi atau terpotong.",
    ],
  },
  {
    version: "v1.7.1",
    date: "2026-05-07",
    title: "Perbaikan tampilan mobile dashboard",
    description: "Rilis patch untuk merapikan tampilan mobile dashboard, Akun & Dompet, detail akun, dan validasi pilihan tipe akun.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.1`,
    changes: [
      "Merapikan kartu dashboard, budget, riwayat transaksi, dan tombol aksi agar lebih nyaman digunakan di layar kecil.",
      "Memperbaiki tampilan Akun & Dompet mobile agar nama akun, saldo, ringkasan aset/utang, dan transaksi terbaru tidak terpotong.",
      "Mengaktifkan horizontal scroll riwayat transaksi di dashboard dan detail akun pada mobile.",
      "Memperbaiki header detail akun agar tombol Tambah Transaksi tidak menutup rincian atau deskripsi akun.",
      "Memperbaiki edge case pilihan tipe akun seperti Lainnya (Aset) yang bisa dianggap belum dipilih saat menambah akun.",
    ],
  },
  {
    version: "v1.7.0",
    date: "2026-05-07",
    title: "Enkripsi token Google OAuth",
    description: "BudgetIn memperkuat penyimpanan token Google OAuth dengan enkripsi application-level dan migrasi bertahap untuk token lama.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.0`,
    changes: [
      "Mengenkripsi Google access token dan refresh token sebelum disimpan ke database.",
      "Menambahkan pembacaan token backward-compatible agar token plaintext lama tetap bisa digunakan dan dienkripsi ulang bertahap.",
      "Menghapus exposure access token Google dari session client NextAuth.",
      "Menambahkan script dry-run untuk migrasi token lama serta test enkripsi/token.",
    ],
  },
  {
    version: "v1.6.5",
    date: "2026-05-07",
    title: "Perbaikan waktu transaksi prompt",
    description: "Rilis patch untuk memastikan transaksi dari prompt memakai waktu submit real-time saat user tidak menyebut jam eksplisit.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.5`,
    changes: [
      "Menghapus default jam preset untuk kata pagi, siang, sore, dan malam pada prompt transaksi.",
      "Memastikan prompt tanpa jam eksplisit memakai waktu submit real-time Asia/Jakarta.",
      "Tetap mempertahankan parsing jam eksplisit seperti jam 1 atau pukul 08:30.",
      "Menambahkan test untuk menjaga perilaku waktu transaksi prompt.",
    ],
  },
  {
    version: "v1.6.4",
    date: "2026-05-07",
    title: "Hardening edit tipe akun",
    description: "Rilis patch lanjutan untuk menutup edge case pada tambah/edit akun dan menjaga validasi tipe akun lebih konsisten.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.4`,
    changes: [
      "Memastikan edit akun database benar-benar menyimpan perubahan tipe akun.",
      "Menyembunyikan tipe akun nonaktif dari pilihan tambah akun, kecuali tipe tersebut sedang dipakai akun yang diedit.",
      "Membersihkan field kartu kredit saat akun dipindahkan ke tipe non-kartu dan memperketat validasi tanggal kartu kredit di server.",
      "Menangani kegagalan load tipe akun tanpa membuat halaman terus loading.",
    ],
  },
  {
    version: "v1.6.3",
    date: "2026-05-07",
    title: "Perbaikan pilihan tipe akun",
    description: "Rilis patch untuk memastikan modal Tambah Akun selalu menyimpan pilihan tipe akun yang valid sebelum akun dibuat.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.3`,
    changes: [
      "Memperbaiki error Tipe akun harus dipilih yang bisa muncul walau user sudah memilih tipe akun seperti Lainnya (Aset).",
      "Menyinkronkan pilihan tipe akun ketika daftar tipe akun selesai dimuat atau berubah.",
      "Mencegah submit akun baru sebelum tipe akun valid tersedia di form.",
    ],
  },
  {
    version: "v1.6.2",
    date: "2026-05-06",
    title: "Perbaikan layout admin dan riwayat transaksi mobile",
    description: "Rilis patch untuk memperbaiki layout admin panel yang terpotong saat sidebar terbuka dan menampilkan sumber akun di riwayat transaksi mobile.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.2`,
    changes: [
      "Memperbaiki admin panel yang terpotong saat sidebar terbuka dengan mengaktifkan horizontal scroll dan padding topbar mobile.",
      "Menampilkan nama akun sumber di bawah deskripsi transaksi pada tampilan mobile di riwayat transaksi dashboard.",
    ],
  },
  {
    version: "v1.6.1",
    date: "2026-05-06",
    title: "Perbaikan tampilan mobile dan jam transaksi",
    description: "Rilis patch untuk merapikan ringkasan Akun & Dompet di layar kecil dan memastikan jam transaksi manual tetap akurat saat submit.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.1`,
    changes: [
      "Mencegah nominal Total Aset, Kekayaan Bersih, dan Total Utang saling bertumpuk di halaman Akun & Dompet mobile.",
      "Membuat ukuran nominal ringkasan akun lebih responsif dan aman untuk nilai panjang.",
      "Memastikan form transaksi manual memakai jam terkini saat submit kecuali user mengubah jam secara manual.",
    ],
  },
  {
    version: "v1.6.0",
    date: "2026-05-05",
    title: "SEO audit dan halaman publik",
    description: "Halaman publik BudgetIn diperkuat untuk crawlability, metadata sharing, trust signal, dan aksesibilitas berdasarkan audit SquirrelScan.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.0`,
    changes: [
      "Menambahkan robots.txt dan sitemap.xml untuk halaman publik BudgetIn.",
      "Memperkuat metadata SEO global, canonical URL, Open Graph, Twitter card, dan preview image.",
      "Menambahkan halaman Tentang dan Kontak sebagai trust pages publik.",
      "Menandai halaman auth sebagai noindex agar login/demo tidak ditargetkan SEO.",
      "Menambahkan footer publik, internal link legal/informasi, skip link, dan polish konten privacy/homepage.",
    ],
  },
  {
    version: "v1.5.0",
    date: "2026-05-05",
    title: "Jam transaksi end-to-end",
    description: "Transaksi sekarang menyimpan tanggal dan jam terpisah, bisa diinput manual, diedit, ditampilkan, diurutkan, serta dipahami dari prompt AI.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.5.0`,
    changes: [
      "Menambahkan input jam di form transaksi manual dan modal edit transaksi.",
      "Menampilkan jam transaksi di daftar transaksi serta mengurutkan riwayat berdasarkan tanggal dan jam.",
      "Menambahkan field time di database dan kolom time di Google Sheets Transaksi kolom L tanpa menggeser kolom lama.",
      "Membuat AI prompt memahami waktu seperti jam 14:30, jam 2 siang, tadi pagi, sore, malam, dan semalam.",
      "Memastikan backup/restore, calendar, account detail, dan bill payment kompatibel dengan jam transaksi.",
    ],
  },
  {
    version: "v1.4.0",
    date: "2026-05-05",
    title: "Reset data dan delete account di Settings",
    description: "User sekarang bisa mereset data, mereset setup akun, dan menghapus akun langsung dari halaman Settings dengan konfirmasi eksplisit.",
    type: "release",
    changes: [
      "Menambahkan halaman Akun & Data untuk reset data finansial, reset setup akun, dan delete account.",
      "Mengosongkan data Google Sheets untuk user Sheets tanpa menghapus file Drive.",
      "Menambahkan proteksi confirmation text sebelum aksi destruktif diproses server.",
      "Menyiapkan ulang kategori dan tipe akun default setelah reset data.",
    ],
  },
  {
    version: "v1.3.1",
    date: "2026-05-05",
    title: "Perbaikan Google Sheets setup lock",
    description: "Dashboard tidak lagi terkunci di layar migrasi fallback saat data Google Sheets sudah sesuai.",
    type: "fix",
    changes: [
      "Menambahkan opsi untuk menandai Google Sheets setup selesai tanpa restore data.",
      "Mempertahankan blokir migrasi otomatis saat target Sheets sudah berisi data agar tidak terjadi duplikasi.",
      "Membuka kembali akses dashboard untuk akun Google yang sudah memiliki data Sheets valid.",
    ],
  },
  {
    version: "v1.3.0",
    date: "2026-05-05",
    title: "Backup Restore dan Google Permission Migration",
    description: "BudgetIn sekarang mendukung backup/restore lintas storage serta recovery akun Google yang perlu permission Sheets dan Drive.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/commit/0f5e78e`,
    changes: [
      "Menambahkan Backup & Restore JSON untuk migrasi data Database dan Google Sheets.",
      "Mendukung restore Database ke Database, Database ke Google Sheets, Google Sheets ke Database, dan Google Sheets ke Google Sheets.",
      "Memblok partial consent Google agar akun baru tidak masuk ke fallback database diam-diam.",
      "Menambahkan recovery flow untuk akun Google yang perlu reconnect permission Sheets dan Drive.",
      "Menambahkan preview dan eksekusi migrasi data fallback ke Google Sheets dengan marker idempotency.",
      "Menampilkan status Google setup required di admin panel agar issue setup lebih mudah dipantau.",
    ],
  },
  {
    version: "v1.0.0",
    date: "2026-05-05",
    title: "Production changelog untuk user",
    description: "User sekarang bisa melihat daftar update production langsung dari dashboard BudgetIn.",
    type: "release",
    changes: [
      "Menambahkan halaman update/changelog yang bisa diakses user dari dashboard.",
      "Menampilkan ringkasan perubahan production dengan versi, tanggal, dan referensi GitHub.",
      "Menyiapkan alur version control berbasis Semantic Versioning untuk rilis berikutnya.",
    ],
  },
  {
    version: "v0.1.0",
    date: "2026-05-05",
    title: "Login demo lebih stabil",
    description: "Perbaikan pada pengalaman akses demo agar proses login tidak mudah timeout.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/commit/9a58ffb`,
    changes: [
      "Menangani timeout pada demo login di halaman autentikasi.",
      "Membuat akses demo lebih konsisten untuk user yang mencoba BudgetIn pertama kali.",
    ],
  },
  {
    version: "v0.1.0",
    date: "2026-05-05",
    title: "Akses akun demo dari homepage",
    description: "User baru dapat mencoba BudgetIn lebih cepat melalui akses demo dari halaman utama.",
    type: "improvement",
    githubUrl: `${githubRepositoryUrl}/commit/df67fc1`,
    changes: [
      "Menambahkan akses akun demo dari homepage.",
      "Mempercepat onboarding user yang ingin melihat fitur BudgetIn tanpa setup awal penuh.",
    ],
  },
  {
    version: "v0.1.0",
    date: "2026-05-05",
    title: "Admin panel command center",
    description: "Panel admin diperbarui untuk memantau user, status data, dan metrik operasional dengan lebih jelas.",
    type: "improvement",
    githubUrl: `${githubRepositoryUrl}/commit/b046703`,
    changes: [
      "Menambahkan KPI user, status verifikasi, mode data, dan metrik aktivitas.",
      "Menyediakan tabel user dengan pencarian, filter, sorting, dan pagination.",
      "Merapikan tampilan admin agar lebih siap untuk operasional production.",
    ],
  },
];

export function getLatestChangelogItem() {
  return changelogItems[0];
}
