export type ChangelogType = "release" | "improvement" | "fix";

export type ChangelogItem = {
  version: string;
  date: string;
  title: string;
  description: string;
  type: ChangelogType;
  changes: string[];
  githubUrl?: string;
};

export const githubRepositoryUrl = "https://github.com/netalone10/BudgetIn";

export const changelogItems: ChangelogItem[] = [
  {
    version: "v1.13.4",
    date: "2026-06-01",
    title: "Transaksi Berulang Tersinkron untuk Pengguna Google Sheets",
    description: "Memperbaiki bug di mana transaksi berulang (otomatis maupun tombol Catat) pengguna Google Sheets tertulis ke database internal, bukan ke Google Sheets — sehingga tidak pernah muncul di dashboard dan laporan.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.13.4`,
    changes: [
      "Transaksi berulang pengguna Google Sheets kini ditulis langsung ke Google Sheets (sebelumnya hanya ke database internal sehingga tidak tampil di dashboard/laporan).",
      "Tombol \"Catat\" pada item berulang kini benar-benar mencatat transaksi ke ledger yang tepat (Sheets untuk pengguna Google, database untuk pengguna email).",
      "Dashboard otomatis di-refresh (cache di-invalidate) setiap kali transaksi berulang tercatat, baik via cron maupun manual.",
    ],
  },
  {
    version: "v1.13.3",
    date: "2026-06-01",
    title: "Peringatan Budget, Insight Tahan Gangguan & Dashboard Lebih Cepat",
    description: "Menambahkan kartu peringatan budget di dashboard, membuat AI Analyst tetap menampilkan insight meski layanan AI sedang bermasalah, serta mempercepat waktu muat halaman dashboard.",
    type: "improvement",
    githubUrl: `${githubRepositoryUrl}/tree/v1.13.3`,
    changes: [
      "Menambahkan kartu Peringatan Budget di dashboard — muncul otomatis saat pengeluaran kategori mendekati (≥80%) atau melewati (≥100%) budget, lengkap dengan progress bar dan persentase.",
      "AI Analyst kini tetap menampilkan insight deterministik (health score, breakdown kategori, pengeluaran terbesar, rekomendasi otomatis) meskipun layanan AI sedang tidak tersedia — sebelumnya seluruh halaman gagal saat AI bermasalah.",
      "Mempercepat waktu muat dashboard: sapaan/greeting kini dirender langsung di server sehingga halaman terasa tampil lebih cepat (perbaikan Largest Contentful Paint).",
      "Menghapus font yang tidak terpakai untuk mengurangi beban unduhan di setiap halaman.",
    ],
  },
  {
    version: "v1.13.2",
    date: "2026-06-01",
    title: "Perbaikan Transaksi Berulang & Export CSV",
    description: "Memperbaiki halaman Berulang yang error tidak bisa dibuka, serta transaksi berulang yang sudah lewat jatuh tempo (overdue) tidak pernah tercatat otomatis. Menambahkan fitur export transaksi ke CSV di halaman Transaksi.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.13.2`,
    changes: [
      "Memperbaiki halaman Berulang yang gagal terbuka (\"Terjadi kesalahan\") akibat perubahan format respons API menjadi { data, pagination }.",
      "Transaksi berulang yang sudah lewat jatuh tempo (overdue) kini ikut tercatat otomatis saat cron berjalan — sebelumnya hanya item yang jatuh tempo tepat hari ini yang ditangkap, sehingga item terlambat terlantar.",
      "Menambahkan tombol Export CSV di halaman Transaksi untuk mengunduh transaksi periode aktif (kolom Tanggal, Waktu, Tipe, Kategori, Nominal, Akun, Akun Tujuan, Catatan).",
    ],
  },
  {
    version: "v1.13.1",
    date: "2026-05-30",
    title: "Konsistensi angka & label antar halaman",
    description: "Perbaikan bug di mana Dashboard menampilkan angka berbeda dari Report/Rincian karena perbedaan kalkulasi Math.abs, isEquityTransaction, dan filter period Sheets. Plus perbaikan label surplus/defisit dan text terpotong di mobile.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.13.1`,
    changes: [
      "Dashboard dan Analyst sekarang menampilkan 'defisit' saat nilai negatif, bukan tetap 'surplus'.",
      "KPICard trend text sekarang wrap 2 baris (line-clamp-2) agar tidak terpotong di mobile.",
      "Samakan Dashboard dengan Report: semua perhitungan pakai Math.abs(t.amount) dan isEquityTransaction.",
      "Tambah handler 'hari ini' dan 'kemarin' di sheets.ts — sebelumnya fallback return semua data.",
    ],
  },
  {
    version: "v1.13.0",
    date: "2026-05-29",
    title: "Laporan Keuangan lengkap & konsistensi akuntansi",
    description: "Halaman Report kini menyajikan tiga laporan keuangan standar — Income Statement, Statement of Owner's Equity, dan Balance Sheet — di atas fondasi akuntansi yang konsisten: Aset − Liabilitas = Ekuitas. Angka pemasukan/pengeluaran disamakan di seluruh aplikasi, plus menyusulkan fitur lupa password dan welcome email.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.13.0`,
    changes: [
      "Menambahkan sub-menu Laporan Keuangan di halaman Report dengan switcher dua level: Income Statement (Laba Rugi), Statement of Owner's Equity (Perubahan Ekuitas), dan Balance Sheet (Neraca).",
      "Statement of Owner's Equity menampilkan waterfall ekuitas: Modal Awal → + Laba Bersih → − Penarikan (tabungan/investasi) → ± Penyesuaian Ekuitas → Modal Akhir, lengkap dengan baris rekonsiliasi sehingga laporan selalu balance.",
      "Balance Sheet menyajikan snapshot per tanggal (date picker) dengan kolom Aset vs Liabilitas + Ekuitas dan banner identitas Aset = Liabilitas + Ekuitas.",
      "Ekuitas pada Balance Sheet dihitung konsisten dengan Kekayaan Bersih di dashboard (total aset − total liabilitas bertanda) sehingga angkanya cocok persis.",
      "Menyamakan total Pemasukan & Pengeluaran di dashboard dengan halaman Report dan Rincian — setoran tabungan/investasi dan transaksi equity tidak lagi ikut terhitung sebagai pemasukan/pengeluaran.",
      "Memperlakukan Saldo Awal dan Penyesuaian Saldo sebagai mutasi ekuitas murni (helper isEquityTransaction) — dikecualikan dari laba rugi secara konsisten di dashboard, report, rincian, analyst, dan cashflow.",
      "Menambahkan saldo akun 'as of date' (getAccountBalancesAsOf) sebagai dasar perhitungan neraca dan ekuitas per periode.",
      "Menambahkan fitur Lupa Password (forgot password flow) lengkap dengan email reset.",
      "Mengirim welcome email otomatis saat pengguna pertama kali login via Google.",
      "Meningkatkan perceived performance dengan klik instan di semua halaman.",
      "Memperbaiki bug akun transfer yang tidak tersimpan saat mengedit transaksi.",
      "Filter \"Minggu ini\" di Google Sheets sekarang pakai Monday-Sunday calendar week (sama dengan DB). Sebelumnya Sheets user melihat rolling 7 hari terakhir.",
    ],
  },
  {
    version: "v1.12.0",
    date: "2026-05-13",
    title: "Rincian Pemasukan & Pengeluaran per kategori",
    description: "Halaman baru /dashboard/details untuk drill-down cepat per kategori — accordion expand, filter periode & pencarian, share bar kontribusi, dan edit/hapus inline. Angka konsisten dengan laporan keuangan.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.12.0`,
    changes: [
      "Menambahkan halaman Rincian (/dashboard/details) dengan sub-tab Pemasukan dan Pengeluaran dalam satu tampilan.",
      "Mengelompokkan transaksi per kategori dengan accordion — klik baris untuk expand dan lihat transaksi anggotanya secara lazy-mount.",
      "Menampilkan share bar kontribusi tiap kategori terhadap total tab aktif beserta badge jumlah transaksi.",
      "Menyediakan filter periode (hari ini / minggu ini / bulan ini / bulan lalu / custom range), pencarian teks, filter akun, dan filter kategori dengan semantik AND.",
      "Mendukung edit dan hapus transaksi inline langsung dari rincian kategori tanpa berpindah halaman.",
      "Memastikan angka per kategori konsisten dengan halaman Report — rule eksklusi Saldo Awal, transfer principal, dan savings identik.",
      "Menambahkan entri navigasi Rincian di sidebar grup Insights antara Kalender dan Report.",
      "Menambahkan avatar picker Dicebear untuk pengguna email.",
      "Menambahkan kartu Runway Kas di dashboard — estimasi berapa bulan bertahan tanpa pemasukan.",
    ],
  },
  {
    version: "v1.11.0",
    date: "2026-05-13",
    title: "Performa dashboard dan keamanan email",
    description: "Rilis mayor yang mempercepat waktu muat dashboard dengan cross-request cache, streaming Suspense, dan SWR pattern di client — serta menutup celah hyperlink injection pada template email.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.11.0`,
    changes: [
      "Menambahkan cross-request TTL cache (30 detik) pada data dashboard sehingga halaman yang dibuka berulang tidak memicu query database/Sheets ulang.",
      "Menambahkan invalidasi cache otomatis di semua API mutasi (transaksi, budget, akun) agar data tetap fresh setelah perubahan.",
      "Memecah Suspense boundary dashboard menjadi dua zona: KPI/ringkasan stream lebih dulu, lalu riwayat transaksi dan budget menyusul secara progresif.",
      "Mengimplementasikan stale-while-revalidate di client — data lama langsung ditampilkan tanpa loading spinner, refresh berjalan di background.",
      "Menambahkan optimistic update saat mencatat transaksi — UI langsung berubah sebelum server merespons, dengan rollback otomatis jika gagal.",
      "Memanfaatkan ETag dan header If-None-Match pada fetch client untuk mengurangi payload transfer (304 Not Modified).",
      "Menutup celah hyperlink injection di email verifikasi, reset password, dan pengingat recurring — nama user kini di-escape HTML sebelum dirender ke template.",
      "Menambahkan validasi nama pada registrasi — nama yang mengandung URL, tag HTML, atau pola domain ditolak dengan pesan error yang jelas.",
      "Membuat modul sanitasi nama (lib/name-validation.ts) sebagai defense-in-depth layer yang bisa dipakai di endpoint lain.",
    ],
  },
  {
    version: "v1.10.1",
    date: "2026-05-12",
    title: "Perbaikan layout mobile dashboard",
    description: "Rilis patch untuk memperbaiki elemen UI yang terpotong di mobile — badge budget, surplus cashflow, dan tombol aksi cepat.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.10.1`,
    changes: [
      "Memperbaiki badge status budget (Over Budget, Hampir Limit, Aman) yang terpotong di mobile dengan mengubah layout menjadi vertikal pada layar kecil.",
      "Memperbaiki bar surplus/defisit cashflow yang overflow di mobile dengan menata label dan nominal secara vertikal.",
      "Memperbaiki tombol aksi cepat (Pengeluaran, Pemasukan, Transfer, Refresh) yang terpotong di mobile dengan mengurangi padding dan ukuran teks pada layar kecil.",
    ],
  },
  {
    version: "v1.10.0",
    date: "2026-05-10",
    title: "Recurring Transactions: gantikan Tagihan Rutin dengan transaksi berulang yang fleksibel",
    description: "Fitur Tagihan Rutin diperluas menjadi sistem transaksi berulang yang lebih lengkap. Sekarang mendukung pengeluaran, pemasukan, dan transfer dengan frekuensi custom (harian/mingguan/bulanan/tahunan + interval N), plus integrasi opsional dengan goal tabungan.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.10.0`,
    changes: [
      "Mengganti model RecurringBill menjadi RecurringTransaction yang mendukung tipe expense, income, dan transfer dalam satu entitas.",
      "Menambahkan frekuensi fleksibel (harian/mingguan/bulanan/tahunan) dengan interval N, sehingga bisa membuat item berulang seperti 'setiap 2 minggu' atau 'setiap 3 bulan'.",
      "Mendukung tanggal mulai (start date) dan tanggal akhir (end date) opsional untuk membatasi periode aktif item berulang.",
      "Mendukung integrasi opsional ke goal tabungan — kontribusi otomatis tercatat saat transaksi berulang dijalankan.",
      "Auto-record transfer sekarang membuat pasangan transaction transfer_out dan transfer_in dalam satu prisma.$transaction agar atomic dengan transferId yang sama.",
      "Idempotency key per occurrence diturunkan menjadi yyyy-MM-dd, sehingga frekuensi mingguan dan harian bisa memiliki banyak occurrence dalam satu bulan tanpa konflik.",
      "Halaman Tagihan diganti menjadi halaman Berulang di /dashboard/recurring dengan filter per tipe (Pengeluaran/Pemasukan/Transfer) dan per status (Terlambat/Hari Ini/Segera/Sudah Catat/Mendatang).",
      "Pengingat email digeneralisasi untuk semua tipe (sebelumnya hardcoded sebagai 'tagihan'), termasuk tautan kelola pengingat ke halaman Berulang.",
      "Cron harian dipindah dari /api/cron/bills ke /api/cron/recurring dengan branching logic per tipe.",
      "Bumping backup schema ke versi 2 dengan auto-migration dari v1 — file backup lama tetap bisa di-restore tanpa konversi manual.",
      "Menambahkan SQL migration script idempotent (scripts/migrate-recurring-transactions.sql) yang me-rename tabel dan mentransform due_day menjadi start_date tanpa kehilangan data existing.",
      "Menambahkan redirect otomatis dari /dashboard/bills ke /dashboard/recurring agar bookmark dan URL lama tetap berfungsi.",
    ],
  },
  {
    version: "v1.9.2",
    date: "2026-05-09",
    title: "React Doctor fixes dan hardening input transaksi",
    description: "Rilis patch untuk membersihkan issue React/Next.js lint-doctor, memperkuat parsing transaksi, dan memastikan setting tipe budget kategori terbaca konsisten.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/commit/e5ffd4c`,
    changes: [
      "Memperbaiki temuan React Doctor di halaman dashboard, admin, auth, akun, budget, tagihan, kalender, cashflow, changelog, dan komponen UI terkait.",
      "Memperkuat parsing nominal transaksi agar input natural seperti ribuan/jutaan lebih aman dan konsisten.",
      "Membersihkan note transaksi dari hasil parsing agar catatan yang tersimpan lebih rapi.",
      "Memastikan pilihan kategori Fixed/Variable yang sudah tersimpan di database ikut terbaca pada data budget dan dashboard.",
    ],
  },
  {
    version: "v1.9.1",
    date: "2026-05-09",
    title: "Compatibility kategori budget type",
    description: "Rilis patch untuk menjaga kompatibilitas produksi saat kolom budget type belum tersedia di sebagian environment database.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/commit/fd4411f`,
    changes: [
      "Menambahkan fallback pada API kategori ketika kolom budget_type belum tersedia di database production.",
      "Menjaga alur tagihan, transaksi manual, cron bills, dan backup tetap berjalan tanpa bergantung langsung pada field budget type.",
      "Memastikan kategori lama tetap mendapatkan tipe Fixed/Variable melalui fallback dari nama kategori.",
    ],
  },
  {
    version: "v1.9.0",
    date: "2026-05-08",
    title: "Akun Demo, Audit Keamanan, dan Perbaikan Data Integrity",
    description: "Rilis mayor yang mengamankan akun demo dengan pembacaan-only, menjalankan audit lengkap terhadap seluruh codebase, dan memperbaiki beberapa issue kritis terkait presisi data dan race condition.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.9.0`,
    changes: [
      "Membatasi akun demo ke mode pembacaan-only — semua tombol aksi (tambah, edit, hapus, reset) tersembunyi, semua write API routes dikembalikan 403 Forbidden.",
      "Menambahkan banner Demo Mode dan countdown timer 15 menit yang otomatis logout jika tidak ada aktivitas.",
      "Memblokir password panjang (>128 karakter) untuk mencegah bcrypt DoS.",
      "Memperbaiki urutan validasi password — cek sama dengan password lama sebelum menjalankan bcrypt.compare yang mahal.",
      "Menambahkan pengecekan null CRON_SECRET agar endpoint cron tidak bisa di-bypass dengan string 'Bearer undefined'.",
      "Mengonversi Budget.amount dan SavingsGoal.targetAmount dari Float ke Decimal(19,4) untuk presisi data keuangan.",
      "Memperbaiki race condition di cron auto-record — transaction.create sekarang berada di dalam blok prisma.$transaction sehingga semua operasi bersifat atomic.",
      "Menambahkan foreign key constraint pada SavingsContribution.transactionId dengan onDelete: Cascade, mencegah data orphan saat transaksi dihapus.",
      "Mengoptimasi query transaksi akun — Prisma sekarang menggunakan take:limit dan database-level aggregation daripada memuat semua baris ke memori.",
    ],
  },
  {
    version: "v1.8.1",
    date: "2026-05-08",
    title: "Kontrol tipe budget kategori",
    description: "Rilis patch untuk menambahkan kontrol Fixed/Variable pada kategori budget dan memakai setting tersebut di semua tampilan budget.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.8.1`,
    changes: [
      "Menambahkan field budget type per kategori agar Fixed atau Variable bisa diatur dari Tools Kelola Kategori.",
      "Mengganti penentuan Fixed/Variable dari keyword hardcoded menjadi setting kategori yang tersimpan di database, dengan fallback untuk data lama.",
      "Memakai tipe budget kategori pada halaman Budget, dashboard Vs Budget, dan Status Budget untuk kalkulasi prorata dan progress bar.",
      "Menyertakan tipe budget kategori dalam API, data dashboard, backup/restore, dan sinkronisasi schema Prisma.",
    ],
  },
  {
    version: "v1.8.0",
    date: "2026-05-08",
    title: "Pembaruan visual dashboard dan progress budget",
    description: "Rilis minor untuk memperbarui tema visual dashboard, merapikan komponen UI utama, dan memperjelas progress budget terhadap total serta prorata.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.8.0`,
    changes: [
      "Mengubah dark theme ke gaya command center dengan surface gelap berlapis dan aksen Neon Lime yang lebih fokus.",
      "Merapikan sidebar, dashboard, form transaksi, kartu ringkasan, tab analytics, dan komponen UI agar lebih konsisten dengan token desain baru.",
      "Menambahkan progress bar budget berbasis total budget dengan marker prorata untuk kategori variable di halaman Budget, dashboard Vs Budget, dan Status Budget.",
      "Menambahkan dokumentasi produk, roadmap, dan TDD sebagai referensi pengembangan lanjutan.",
    ],
  },
  {
    version: "v1.7.3",
    date: "2026-05-08",
    title: "Perbaikan error server dan layout mobile",
    description: "Rilis patch untuk mencegah crash server component akibat timeout query Google Setup dan memperbaiki konten terpotong di mobile.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.3`,
    changes: [
      "Mencegah crash server component di halaman dashboard saat query Prisma ke Google Setup state timeout atau gagal.",
      "Error Google Setup sekarang di-graceful fallback ke state normal alih-alih menampilkan error boundary.",
      "Memperbaiki konten dashboard terpotong di mobile dengan mengganti overflow-x-hidden menjadi overflow-x-clip.",
      "Menambahkan min-w-0 di flex child layout dashboard agar konten tidak melebihi lebar parent.",
    ],
  },
  {
    version: "v1.7.2",
    date: "2026-05-07",
    title: "Perbaikan prompt real-time dan audit mobile",
    description: "Rilis patch untuk memastikan prompt tanpa jam eksplisit memakai waktu submit real-time dan memperkuat layout mobile di halaman utama dashboard.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.2`,
    changes: [
      "Mengabaikan waktu hasil AI seperti 08:00 atau 00:00 jika user tidak menyebut jam eksplisit di prompt transaksi.",
      "Memastikan prompt seperti beli ketoprak 20rb cash dicatat dengan waktu submit real-time Asia/Jakarta.",
      "Memperketat instruksi AI agar tidak membuat preset jam untuk pagi, siang, sore, malam, atau tadi tanpa angka jam eksplisit.",
      "Menambahkan test regresi untuk menjaga fallback waktu prompt tetap real-time.",
      "Menghapus blok Input, Output, dan Rhythm dari hero dashboard agar user langsung masuk ke fitur utama.",
      "Merapikan mobile view dashboard, detail akun, budget, calendar, cashflow, tipe akun, tabungan, dan tagihan rutin agar nominal penting tidak tersembunyi atau terpotong.",
    ],
  },
  {
    version: "v1.7.1",
    date: "2026-05-07",
    title: "Perbaikan tampilan mobile dashboard",
    description: "Rilis patch untuk merapikan tampilan mobile dashboard, Akun & Dompet, detail akun, dan validasi pilihan tipe akun.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.1`,
    changes: [
      "Merapikan kartu dashboard, budget, riwayat transaksi, dan tombol aksi agar lebih nyaman digunakan di layar kecil.",
      "Memperbaiki tampilan Akun & Dompet mobile agar nama akun, saldo, ringkasan aset/utang, dan transaksi terbaru tidak terpotong.",
      "Mengaktifkan horizontal scroll riwayat transaksi di dashboard dan detail akun pada mobile.",
      "Memperbaiki header detail akun agar tombol Tambah Transaksi tidak menutup rincian atau deskripsi akun.",
      "Memperbaiki edge case pilihan tipe akun seperti Lainnya (Aset) yang bisa dianggap belum dipilih saat menambah akun.",
    ],
  },
  {
    version: "v1.7.0",
    date: "2026-05-07",
    title: "Enkripsi token Google OAuth",
    description: "BudgetIn memperkuat penyimpanan token Google OAuth dengan enkripsi application-level dan migrasi bertahap untuk token lama.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.7.0`,
    changes: [
      "Mengenkripsi Google access token dan refresh token sebelum disimpan ke database.",
      "Menambahkan pembacaan token backward-compatible agar token plaintext lama tetap bisa digunakan dan dienkripsi ulang bertahap.",
      "Menghapus exposure access token Google dari session client NextAuth.",
      "Menambahkan script dry-run untuk migrasi token lama serta test enkripsi/token.",
    ],
  },
  {
    version: "v1.6.5",
    date: "2026-05-07",
    title: "Perbaikan waktu transaksi prompt",
    description: "Rilis patch untuk memastikan transaksi dari prompt memakai waktu submit real-time saat user tidak menyebut jam eksplisit.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.5`,
    changes: [
      "Menghapus default jam preset untuk kata pagi, siang, sore, dan malam pada prompt transaksi.",
      "Memastikan prompt tanpa jam eksplisit memakai waktu submit real-time Asia/Jakarta.",
      "Tetap mempertahankan parsing jam eksplisit seperti jam 1 atau pukul 08:30.",
      "Menambahkan test untuk menjaga perilaku waktu transaksi prompt.",
    ],
  },
  {
    version: "v1.6.4",
    date: "2026-05-07",
    title: "Hardening edit tipe akun",
    description: "Rilis patch lanjutan untuk menutup edge case pada tambah/edit akun dan menjaga validasi tipe akun lebih konsisten.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.4`,
    changes: [
      "Memastikan edit akun database benar-benar menyimpan perubahan tipe akun.",
      "Menyembunyikan tipe akun nonaktif dari pilihan tambah akun, kecuali tipe tersebut sedang dipakai akun yang diedit.",
      "Membersihkan field kartu kredit saat akun dipindahkan ke tipe non-kartu dan memperketat validasi tanggal kartu kredit di server.",
      "Menangani kegagalan load tipe akun tanpa membuat halaman terus loading.",
    ],
  },
  {
    version: "v1.6.3",
    date: "2026-05-07",
    title: "Perbaikan pilihan tipe akun",
    description: "Rilis patch untuk memastikan modal Tambah Akun selalu menyimpan pilihan tipe akun yang valid sebelum akun dibuat.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.3`,
    changes: [
      "Memperbaiki error Tipe akun harus dipilih yang bisa muncul walau user sudah memilih tipe akun seperti Lainnya (Aset).",
      "Menyinkronkan pilihan tipe akun ketika daftar tipe akun selesai dimuat atau berubah.",
      "Mencegah submit akun baru sebelum tipe akun valid tersedia di form.",
    ],
  },
  {
    version: "v1.6.2",
    date: "2026-05-06",
    title: "Perbaikan layout admin dan riwayat transaksi mobile",
    description: "Rilis patch untuk memperbaiki layout admin panel yang terpotong saat sidebar terbuka dan menampilkan sumber akun di riwayat transaksi mobile.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.2`,
    changes: [
      "Memperbaiki admin panel yang terpotong saat sidebar terbuka dengan mengaktifkan horizontal scroll dan padding topbar mobile.",
      "Menampilkan nama akun sumber di bawah deskripsi transaksi pada tampilan mobile di riwayat transaksi dashboard.",
    ],
  },
  {
    version: "v1.6.1",
    date: "2026-05-06",
    title: "Perbaikan tampilan mobile dan jam transaksi",
    description: "Rilis patch untuk merapikan ringkasan Akun & Dompet di layar kecil dan memastikan jam transaksi manual tetap akurat saat submit.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.1`,
    changes: [
      "Mencegah nominal Total Aset, Kekayaan Bersih, dan Total Utang saling bertumpuk di halaman Akun & Dompet mobile.",
      "Membuat ukuran nominal ringkasan akun lebih responsif dan aman untuk nilai panjang.",
      "Memastikan form transaksi manual memakai jam terkini saat submit kecuali user mengubah jam secara manual.",
    ],
  },
  {
    version: "v1.6.0",
    date: "2026-05-05",
    title: "SEO audit dan halaman publik",
    description: "Halaman publik BudgetIn diperkuat untuk crawlability, metadata sharing, trust signal, dan aksesibilitas berdasarkan audit SquirrelScan.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.6.0`,
    changes: [
      "Menambahkan robots.txt dan sitemap.xml untuk halaman publik BudgetIn.",
      "Memperkuat metadata SEO global, canonical URL, Open Graph, Twitter card, dan preview image.",
      "Menambahkan halaman Tentang dan Kontak sebagai trust pages publik.",
      "Menandai halaman auth sebagai noindex agar login/demo tidak ditargetkan SEO.",
      "Menambahkan footer publik, internal link legal/informasi, skip link, dan polish konten privacy/homepage.",
    ],
  },
  {
    version: "v1.5.0",
    date: "2026-05-05",
    title: "Jam transaksi end-to-end",
    description: "Transaksi sekarang menyimpan tanggal dan jam terpisah, bisa diinput manual, diedit, ditampilkan, diurutkan, serta dipahami dari prompt AI.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/tree/v1.5.0`,
    changes: [
      "Menambahkan input jam di form transaksi manual dan modal edit transaksi.",
      "Menampilkan jam transaksi di daftar transaksi serta mengurutkan riwayat berdasarkan tanggal dan jam.",
      "Menambahkan field time di database dan kolom time di Google Sheets Transaksi kolom L tanpa menggeser kolom lama.",
      "Membuat AI prompt memahami waktu seperti jam 14:30, jam 2 siang, tadi pagi, sore, malam, dan semalam.",
      "Memastikan backup/restore, calendar, account detail, dan bill payment kompatibel dengan jam transaksi.",
    ],
  },
  {
    version: "v1.4.0",
    date: "2026-05-05",
    title: "Reset data dan delete account di Settings",
    description: "User sekarang bisa mereset data, mereset setup akun, dan menghapus akun langsung dari halaman Settings dengan konfirmasi eksplisit.",
    type: "release",
    changes: [
      "Menambahkan halaman Akun & Data untuk reset data finansial, reset setup akun, dan delete account.",
      "Mengosongkan data Google Sheets untuk user Sheets tanpa menghapus file Drive.",
      "Menambahkan proteksi confirmation text sebelum aksi destruktif diproses server.",
      "Menyiapkan ulang kategori dan tipe akun default setelah reset data.",
    ],
  },
  {
    version: "v1.3.1",
    date: "2026-05-05",
    title: "Perbaikan Google Sheets setup lock",
    description: "Dashboard tidak lagi terkunci di layar migrasi fallback saat data Google Sheets sudah sesuai.",
    type: "fix",
    changes: [
      "Menambahkan opsi untuk menandai Google Sheets setup selesai tanpa restore data.",
      "Mempertahankan blokir migrasi otomatis saat target Sheets sudah berisi data agar tidak terjadi duplikasi.",
      "Membuka kembali akses dashboard untuk akun Google yang sudah memiliki data Sheets valid.",
    ],
  },
  {
    version: "v1.3.0",
    date: "2026-05-05",
    title: "Backup Restore dan Google Permission Migration",
    description: "BudgetIn sekarang mendukung backup/restore lintas storage serta recovery akun Google yang perlu permission Sheets dan Drive.",
    type: "release",
    githubUrl: `${githubRepositoryUrl}/commit/0f5e78e`,
    changes: [
      "Menambahkan Backup & Restore JSON untuk migrasi data Database dan Google Sheets.",
      "Mendukung restore Database ke Database, Database ke Google Sheets, Google Sheets ke Database, dan Google Sheets ke Google Sheets.",
      "Memblok partial consent Google agar akun baru tidak masuk ke fallback database diam-diam.",
      "Menambahkan recovery flow untuk akun Google yang perlu reconnect permission Sheets dan Drive.",
      "Menambahkan preview dan eksekusi migrasi data fallback ke Google Sheets dengan marker idempotency.",
      "Menampilkan status Google setup required di admin panel agar issue setup lebih mudah dipantau.",
    ],
  },
  {
    version: "v1.0.0",
    date: "2026-05-05",
    title: "Production changelog untuk user",
    description: "User sekarang bisa melihat daftar update production langsung dari dashboard BudgetIn.",
    type: "release",
    changes: [
      "Menambahkan halaman update/changelog yang bisa diakses user dari dashboard.",
      "Menampilkan ringkasan perubahan production dengan versi, tanggal, dan referensi GitHub.",
      "Menyiapkan alur version control berbasis Semantic Versioning untuk rilis berikutnya.",
    ],
  },
  {
    version: "v0.1.0",
    date: "2026-05-05",
    title: "Login demo lebih stabil",
    description: "Perbaikan pada pengalaman akses demo agar proses login tidak mudah timeout.",
    type: "fix",
    githubUrl: `${githubRepositoryUrl}/commit/9a58ffb`,
    changes: [
      "Menangani timeout pada demo login di halaman autentikasi.",
      "Membuat akses demo lebih konsisten untuk user yang mencoba BudgetIn pertama kali.",
    ],
  },
  {
    version: "v0.1.0",
    date: "2026-05-05",
    title: "Akses akun demo dari homepage",
    description: "User baru dapat mencoba BudgetIn lebih cepat melalui akses demo dari halaman utama.",
    type: "improvement",
    githubUrl: `${githubRepositoryUrl}/commit/df67fc1`,
    changes: [
      "Menambahkan akses akun demo dari homepage.",
      "Mempercepat onboarding user yang ingin melihat fitur BudgetIn tanpa setup awal penuh.",
    ],
  },
  {
    version: "v0.1.0",
    date: "2026-05-05",
    title: "Admin panel command center",
    description: "Panel admin diperbarui untuk memantau user, status data, dan metrik operasional dengan lebih jelas.",
    type: "improvement",
    githubUrl: `${githubRepositoryUrl}/commit/b046703`,
    changes: [
      "Menambahkan KPI user, status verifikasi, mode data, dan metrik aktivitas.",
      "Menyediakan tabel user dengan pencarian, filter, sorting, dan pagination.",
      "Merapikan tampilan admin agar lebih siap untuk operasional production.",
    ],
  },
];

export function getLatestChangelogItem() {
  return changelogItems[0];
}
