const CATEGORY_EMOJI: Record<string, string> = {
  // ── Makanan & Minuman ──────────────────────────────────────────────────────
  makan: "🍔",
  "makan & minum": "🍔",
  makanan: "🍱",
  "makanan & minuman": "🍱",
  minuman: "🥤",
  jajan: "🍰",
  snack: "🍿",
  ngopi: "☕",
  kopi: "☕",
  cafe: "☕",
  restoran: "🍽️",
  restaurant: "🍽️",
  warung: "🍜",
  delivery: "🛵",
  "food delivery": "🛵",

  // ── Transport ─────────────────────────────────────────────────────────────
  transport: "🚗",
  transportasi: "🚗",
  bensin: "⛽",
  bbm: "⛽",
  parkir: "🅿️",
  ojek: "🛵",
  grab: "🚖",
  gojek: "🚖",
  taxi: "🚕",
  taksi: "🚕",
  busway: "🚌",
  bus: "🚌",
  kereta: "🚆",
  krl: "🚆",
  mrt: "🚇",
  pesawat: "✈️",
  toll: "🛣️",
  tol: "🛣️",
  servis: "🔧",
  "servis kendaraan": "🔧",

  // ── Tagihan & Utilitas ────────────────────────────────────────────────────
  tagihan: "⚡",
  "tagihan & utilitas": "⚡",
  utilitas: "⚡",
  listrik: "💡",
  air: "💧",
  pdam: "💧",
  gas: "🔥",
  internet: "📶",
  wifi: "📶",
  pulsa: "📱",
  telepon: "📞",
  tv: "📺",
  "tv kabel": "📺",
  netflix: "📺",
  spotify: "🎵",
  streaming: "📺",
  langganan: "🔔",
  subscription: "🔔",
  iuran: "📋",

  // ── Rumah & Properti ──────────────────────────────────────────────────────
  rumah: "🏠",
  sewa: "🏠",
  "sewa rumah": "🏠",
  "sewa kost": "🏠",
  kost: "🏠",
  kontrakan: "🏠",
  renovasi: "🔨",
  furniture: "🛋️",
  perabot: "🛋️",
  "perlengkapan rumah": "🏡",
  kebersihan: "🧹",
  laundry: "👕",
  cuci: "🧺",

  // ── Kesehatan ─────────────────────────────────────────────────────────────
  kesehatan: "💊",
  obat: "💊",
  "obat-obatan": "💊",
  dokter: "🩺",
  "rumah sakit": "🏥",
  rs: "🏥",
  klinik: "🏥",
  apotek: "💊",
  vitamin: "💊",
  gym: "🏋️",
  "gym & fitness": "🏋️",

  // ── Hiburan & Gaya Hidup ──────────────────────────────────────────────────
  hiburan: "🎮",
  "hiburan & gaya hidup": "🎮",
  game: "🎮",
  gaming: "🎮",
  film: "🎬",
  bioskop: "🎬",
  konser: "🎤",
  musik: "🎵",
  hobi: "🎨",
  buku: "📖",
  komik: "📖",
  karaoke: "🎤",
  pesta: "🎉",
  "nongkrong & hangout": "🥂",
  hangout: "🥂",
  nongkrong: "🥂",
  bar: "🍺",
  alkohol: "🍺",

  // ── Belanja ───────────────────────────────────────────────────────────────
  belanja: "🛒",
  "belanja bulanan": "🛒",
  groceries: "🛒",
  supermarket: "🛒",
  "belanja online": "📦",
  online: "📦",
  shopee: "📦",
  tokopedia: "📦",
  lazada: "📦",
  fashion: "👗",
  baju: "👗",
  pakaian: "👗",
  sepatu: "👟",
  tas: "👜",
  aksesori: "💍",
  aksesoris: "💍",
  kosmetik: "💄",
  kecantikan: "💄",
  skincare: "🧴",
  perawatan: "🧴",
  "perawatan diri": "🧴",
  elektronik: "📱",
  gadget: "📱",
  hp: "📱",
  laptop: "💻",

  // ── Pendidikan ────────────────────────────────────────────────────────────
  pendidikan: "📚",
  sekolah: "🏫",
  kuliah: "🎓",
  kursus: "📝",
  les: "✏️",
  bimbel: "✏️",
  "kursus online": "💻",
  seminar: "🎓",
  pelatihan: "📝",
  training: "📝",
  sertifikasi: "📜",

  // ── Keuangan & Tabungan ───────────────────────────────────────────────────
  tabungan: "🏦",
  "dana darurat": "🛡️",
  asuransi: "🛡️",
  "asuransi jiwa": "🛡️",
  "asuransi kesehatan": "🛡️",
  cicilan: "💳",
  kredit: "💳",
  kpr: "🏠",
  pinjaman: "🏦",
  utang: "💸",
  "bayar utang": "💸",

  // ── Sosial & Keluarga ─────────────────────────────────────────────────────
  hadiah: "🎁",
  "hadiah & kado": "🎁",
  kado: "🎁",
  donasi: "🤝",
  sedekah: "🤲",
  infak: "🤲",
  zakat: "🤲",
  sosial: "🤝",
  keluarga: "👨‍👩‍👧",
  anak: "👶",
  "uang saku": "💸",
  wedding: "💒",
  pernikahan: "💒",
  kondangan: "💒",

  // ── Perjalanan ────────────────────────────────────────────────────────────
  travel: "✈️",
  liburan: "🏖️",
  "liburan & travel": "🏖️",
  "hotel & penginapan": "🏨",
  hotel: "🏨",
  penginapan: "🏨",
  wisata: "🗺️",
  tiket: "🎟️",

  // ── Olahraga ─────────────────────────────────────────────────────────────
  olahraga: "⚽",
  futsal: "⚽",
  badminton: "🏸",
  renang: "🏊",
  lari: "🏃",
  sepeda: "🚴",
  hiking: "🥾",

  // ── Lain-lain ─────────────────────────────────────────────────────────────
  "lain-lain": "📦",
  lainnya: "📌",
  lain: "📦",
  misc: "📦",
  miscellaneous: "📦",
  "tak terduga": "⚠️",
  darurat: "🆘",

  // ── Income — default ──────────────────────────────────────────────────────
  gaji: "💼",
  "gaji & upah": "💼",
  upah: "💼",
  freelance: "💻",
  "pekerjaan sampingan": "💻",
  "side job": "💻",
  bonus: "🎯",
  investasi: "📈",
  saham: "📈",
  reksa: "📈",
  "reksa dana": "📈",
  crypto: "🪙",
  bisnis: "🏢",
  usaha: "🏢",
  thr: "🎊",
  "thr & hadiah": "🎊",
  dividen: "💵",
  "dividen & bunga": "💵",
  bunga: "💵",
  "bunga bank": "💵",

  // ── Income — aliases ──────────────────────────────────────────────────────
  pemasukan: "💰",
  pendapatan: "💰",
  "penghasilan lainnya": "📌",
  pengembalian: "🔄",
  refund: "🔄",
  cashback: "🔄",
  "uang kembali": "🔄",
  warisan: "🏛️",
  "hasil sewa": "🏘️",
  royalti: "✍️",
};

export function getCategoryIcon(name: string): string {
  return CATEGORY_EMOJI[name.toLowerCase()] ?? "📂";
}

export function getCategoryIconForTransaction(
  categoryName: string,
  type?: string
): string {
  if (type === "transfer_out" || type === "transfer_in") return "🔄";
  return getCategoryIcon(categoryName);
}
